import React from 'react';
import { ArrowLeft, Brain, Network, Eye } from 'lucide-react';
import { Link } from 'react-router-dom';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const TemplateBasedGraphModels = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-grow page-container">
        <div className="mb-6">
          <Link 
            to="/theory/module4" 
            className="inline-flex items-center gap-2 text-accent hover:text-accent/80 transition-colors mb-4"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Module 4
          </Link>
          <h1 className="text-4xl font-bold text-foreground mb-4">
            Template Based Graph Models
          </h1>
        </div>

        <div className="space-y-8">
          {/* Hidden Markov Models Section */}
          <div className="bg-card border rounded-lg p-6">
            <div className="flex items-center gap-3 mb-4">
              <Brain className="w-6 h-6 text-accent" />
              <h2 className="text-2xl font-semibold text-foreground">Hidden Markov Models (HMMs)</h2>
            </div>
            
            <p className="text-muted-foreground leading-relaxed mb-4">
              Hidden Markov Models are statistical models where the system being modeled is assumed to be a Markov 
              process with unobserved (hidden) states. The observed data is generated by the hidden states through emission probabilities.
            </p>

            <div className="my-4">
              <img src="/theory-images/module4/img1.png" alt="Hidden Markov Model" className="w-full max-w-md mx-auto rounded-lg shadow-md" />
            </div>

            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">HMM Components</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="bg-muted/30 p-4 rounded-lg">
                    <h4 className="font-semibold text-foreground mb-2">States (Hidden)</h4>
                    <p className="text-muted-foreground text-sm">
                      The underlying states that are not directly observable but influence the observed outputs.
                    </p>
                  </div>
                  <div className="bg-muted/30 p-4 rounded-lg">
                    <h4 className="font-semibold text-foreground mb-2">Observations</h4>
                    <p className="text-muted-foreground text-sm">
                      The visible outputs that are generated by the hidden states according to emission probabilities.
                    </p>
                  </div>
                  <div className="bg-muted/30 p-4 rounded-lg">
                    <h4 className="font-semibold text-foreground mb-2">Transitions</h4>
                    <p className="text-muted-foreground text-sm">
                      Probabilities of moving from one hidden state to another, following the Markov property.
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-accent/5 p-4 rounded-lg border-l-4 border-accent">
                <h3 className="font-semibold text-foreground mb-2">HMM Parameters</h3>
                <ul className="space-y-2 text-muted-foreground text-sm">
                  <li><strong>π:</strong> Initial state probabilities</li>
                  <li><strong>A:</strong> State transition probabilities</li>
                  <li><strong>B:</strong> Emission probabilities (observation probabilities)</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Temporal Models Section */}
          <div className="bg-card border rounded-lg p-6">
            <div className="flex items-center gap-3 mb-4">
              <Network className="w-6 h-6 text-accent" />
              <h2 className="text-2xl font-semibold text-foreground">Temporal Models</h2>
            </div>
            
            <p className="text-muted-foreground leading-relaxed mb-4">
              Temporal models extend graphical models to represent and reason about systems that evolve over time. 
              These models are crucial for sequence analysis and time-series prediction.
            </p>

            <div className="my-4">
              <img src="/theory-images/module4/img2.png" alt="Temporal Models" className="w-full max-w-md mx-auto rounded-lg shadow-md" />
            </div>

            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Dynamic Bayesian Networks</h3>
                <p className="text-muted-foreground mb-3">
                  Dynamic Bayesian Networks (DBNs) extend Bayesian networks to model temporal dependencies. 
                  They consist of a prior network and a transition network that captures how variables change over time.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-muted/30 p-4 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Prior Network</h4>
                  <p className="text-muted-foreground text-sm">
                    Represents the initial state of variables at time t=0.
                  </p>
                </div>
                <div className="bg-muted/30 p-4 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Transition Network</h4>
                  <p className="text-muted-foreground text-sm">
                    Captures dependencies between variables across time slices.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Template Variables Section */}
          <div className="bg-card border rounded-lg p-6">
            <h2 className="text-2xl font-semibold text-foreground mb-4">Template Variables and Template Factors</h2>
            
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Template Representation</h3>
                <p className="text-muted-foreground mb-3">
                  Template-based models allow us to represent repeated structures in graphical models, making them 
                  particularly useful for temporal and relational data.
                </p>

                <div className="my-4">
                  <img src="/theory-images/module4/img3.png" alt="Template Variables" className="w-full max-w-md mx-auto rounded-lg shadow-md" />
                </div>
              </div>

              <div className="bg-muted/30 p-4 rounded-lg">
                <h3 className="font-semibold text-foreground mb-3">Key Concepts</h3>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <span className="text-accent font-bold mt-1">•</span>
                    <span>Template variables represent classes of variables</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-accent font-bold mt-1">•</span>
                    <span>Template factors define relationships between template variables</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-accent font-bold mt-1">•</span>
                    <span>Grounding creates specific instances from templates</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-accent font-bold mt-1">•</span>
                    <span>Enables modeling of large, structured domains</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Directed Probabilistic Models Section */}
          <div className="bg-card border rounded-lg p-6">
            <h2 className="text-2xl font-semibold text-foreground mb-4">Directed Probabilistic Models</h2>
            
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Temporal Dependencies</h3>
                <p className="text-muted-foreground mb-3">
                  Directed models capture causal relationships and temporal dependencies in sequential data, 
                  making them suitable for modeling dynamic systems.
                </p>

                <div className="my-4">
                  <img src="/theory-images/module4/img4.png" alt="Directed Probabilistic Models" className="w-full max-w-md mx-auto rounded-lg shadow-md" />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-accent/5 p-4 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Causal Relationships</h4>
                  <p className="text-muted-foreground text-sm">
                    Directed edges represent causal influences between variables over time.
                  </p>
                </div>
                <div className="bg-accent/5 p-4 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Temporal Ordering</h4>
                  <p className="text-muted-foreground text-sm">
                    Time slices are ordered to maintain temporal consistency.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Undirected Representation Section */}
          <div className="bg-card border rounded-lg p-6">
            <h2 className="text-2xl font-semibold text-foreground mb-4">Undirected Representation</h2>
            
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Markov Random Fields</h3>
                <p className="text-muted-foreground mb-3">
                  Undirected representations capture symmetric dependencies and correlations in temporal data, 
                  often used for modeling spatial and temporal correlations.
                </p>

                <div className="my-4">
                  <img src="/theory-images/module4/img5.png" alt="Undirected Representation" className="w-full max-w-md mx-auto rounded-lg shadow-md" />
                </div>
              </div>

              <div className="bg-muted/30 p-4 rounded-lg">
                <h3 className="font-semibold text-foreground mb-3">Applications</h3>
                <ul className="space-y-1 text-muted-foreground">
                  <li>• Image segmentation and computer vision</li>
                  <li>• Spatial data analysis</li>
                  <li>• Social network analysis</li>
                  <li>• Protein structure prediction</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Structural Uncertainty Section */}
          <div className="bg-card border rounded-lg p-6">
            <div className="flex items-center gap-3 mb-4">
              <Eye className="w-6 h-6 text-accent" />
              <h2 className="text-2xl font-semibold text-foreground">Structural Uncertainty</h2>
            </div>
            
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-3">Model Selection</h3>
                <p className="text-muted-foreground mb-3">
                  When the structure of the graphical model is unknown, we need to consider structural uncertainty 
                  and perform model selection to find the best representation.
                </p>

                <div className="my-4">
                  <img src="/theory-images/module4/img6.png" alt="Structural Uncertainty" className="w-full max-w-md mx-auto rounded-lg shadow-md" />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-muted/30 p-4 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Score-Based Methods</h4>
                  <p className="text-muted-foreground text-sm">
                    Use scoring functions to evaluate different graph structures.
                  </p>
                </div>
                <div className="bg-muted/30 p-4 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Constraint-Based Methods</h4>
                  <p className="text-muted-foreground text-sm">
                    Use statistical tests to determine independence relationships.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default TemplateBasedGraphModels;
